before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
    - amd64
    - arm64
    goos:
      - linux
    main: ./cmd/main.go
archives:
  - id: uncompressed
    format: binary
