name: CI

on:
  push:
    branches:
    - "**"
    tags:
    - "v*.*.*"

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    uses: ./.github/workflows/release.yaml
