name: CI

on:
  push:
    tags:
    - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    needs: [test]
    uses: ./.github/workflows/release.yaml
