name: Build image

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short Git commit hash
        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Always build and tag the image with the Git commit hash
      - name: Build and push Docker image with Git commit hash
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.GIT_COMMIT_HASH }} .
          docker push ghcr.io/${{ github.repository }}:${{ env.GIT_COMMIT_HASH }}

      # Conditional step: Only build and tag with "latest" on the main branch
      - name: Build and push Docker image with "latest" tag
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest

      # Conditional step: Only build and tag with version on tagged pushes
      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/v')  # Only runs if it's a tag push
        run: echo "IMAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image with version tag
        if: startsWith(github.ref, 'refs/tags/v')  # Only runs if it's a tag push
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.IMAGE_VERSION }} .
          docker push ghcr.io/${{ github.repository }}:${{ env.IMAGE_VERSION }}
