name: Release

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.4.0

    - name: Setup Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version-file: "go.mod"

    - name: Run GoRelease
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}