name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.4.0

    - name: Setup Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version-file: "go.mod"

    - name: Install dependencies
      run: go mod tidy
      
    - name: Run tests
      run: go test -v ./...
